- hosts: all
  become: yes
  
  tasks:
    - name: "Установим pip3"
      package:
        name:
          - python3-pip
        state: present
      tags:
        - prepare-servers
  
        
  roles:
    - role: geerlingguy.pip
      tags:
        - prepare-servers
      
    - role: geerlingguy.docker
      tags:
        - prepare-servers