roles:
  - name: geerlingguy.pip
    version: 3.1.0
  - name: geerlingguy.docker
    version: 7.4.0

collections:
  - name: community.docker
    version: 4.6.0
  - name: datadog.dd
    version: 6.1.0

dependencies:
  - requests